### ISSUE TITLE
File to store keys

### ISSUE THREAD

**Issue by runnerbeany** [xSilverdroid/Sonico#11]
Could there possibly be a local file to store keys & admins so they don't have to be retyped after each push?

**Comment by Nevexo** [comment]
copy from discord into build kit but build kit could have a file like username.txt that is gitignored containing tokens and admins if that's what you mean

**Comment by runnerbeany** [comment]
yeah, kinda.
anything that means we don't have to retype it all after each push.

**Comment by Nevexo** [comment]
Okay. feature in development later.

**Comment by runnerbeany** [comment]
great
