### ISSUE TITLE
Case sensitive commands.

### ISSUE THREAD

**Issue by Tvde1** [xSilverdroid/Sonico#12]
Right now, `.help` won't respond to `.Help` or any capitalised char. This is the case for every command.

It's a very easy fix, by adding a `toLowerCase`.

**Comment by xSilverdroid** [comment]
I am wondering who would captalize te commands on purpose, but we will work on it.

**Comment by runnerbeany** [comment]
@xSilverdroid, it could be by accident, many times I have accidentally done .HELP
@Tvde1, I'm doing some edits now so I can look into it.

**Comment by Tvde1** [comment]
Well it's weird to not have it detected.

**Comment by Nevexo** [comment]
It's not 'weird' it's the way messages are detected in the old version of Discord.py, once we convert to cogs (see /rewrite branch) any capitalized messages will be detected.hi
