### ISSUE TITLE
buildkit - Tokens

### ISSUE THREAD

**Issue by runnerbeany** [xSilverdroid/Sonico#15]
When running the bot after setting a buildkit token, I kept getting `4004 - authentication failed`. After looking in `config.json`, it seems that there is an '\n' after the token, I presume this is caused by hitting enter after entering the token. 

**After removing the \n the bot started absolutely fine.**

**Comment by xSilverdroid** [comment]
I guess you fixed it then.

**Comment by runnerbeany** [comment]
How did I fix it? I had to manually edit config.json

**Comment by xSilverdroid** [comment]
Well, config.json works fine for me.

**Comment by runnerbeany** [comment]
Hmm. Try entering a new dev key in build kit.

**Comment by Nevexo** [comment]
Fixed in todays buildkit updates. Closed.
