### ISSUE TITLE
Development Build?

### ISSUE THREAD

**Issue by xSilverdroid** [xSilverdroid/Sonico#5]
I don't think we need a dev build of the bot, since it did not even leave the dev status yet, and if we do, not in this repo.

**Comment by runnerbeany** [comment]
I'll backup the files locally. We'll see what Nevexo thinks.

**Comment by Nevexo** [comment]
Development build is a good idea, do you want to spam everything? We need some sort of dev.

**Comment by xSilverdroid** [comment]
Okay, but let's make the dev build a separate branch instead of putting in both builds

**Comment by xSilverdroid** [comment]
Let's make two branches, master and dev

**Comment by runnerbeany** [comment]
I guess a branch will work. Lets do that then.
